model_llama_id: /workspace/hf_model/Llama-2-7b-chat-hf
model_mistral_id: /workspace/hf_model/Mistral-7B-Instruct-v0.2
model_llama_type: llama
model_mistral_type: mistral
model_embedding: sentence-transformers/all-MiniLM-L6-v2
data:
  train: /workspace/SymbolicResoning/XAI/data/train_v3.json
  val: /workspace/SymbolicResoning/XAI/data/train_v3.json
  test: /workspace/SymbolicResoning/XAI/data/train_v3.json
  batch_size: 1
  num_samples: all

model_config:
  task: text-generation
  max_new_tokens: 2048
  do_sample: true
  repetition_penalty: 1.15
  temperature: 0.1
  top_p: 0.95
  num_beam: 2
  dola_layers: high
  use_cache: true

module_nl2fol:
  base_model: "/workspace/hf_model/Llama-2-7b-chat-hf"
  peft_path: "/workspace/hf_model/LogicLLaMA-7b-direct-translate-delta-v0.1"
  prompt_template_path: "/workspace/SymbolicResoning/XAI/data/prompt_templates"
  load_in_8bit: False
  max_output_len: 256