# from .reasoning import Something
from .template import (
    PARSE_QUESTION, 
    UNDERSTAND_BACKGROUND_PROMPT, 
    UNDERSTAND_BACKGROUND_PROMPT_WITHOUT_PREMISE, 
    REDUCE_AND_MATCHING_PREDICATE_PROMPT, 
    EXTRACT_MAIN_PREDICATE,
    HEAD_INSTRUCTION,
    LOGIC_PROGRAM_EXTRACTION_PROMPTING,
    LOGIC_PROGRAM_EXTRACTION_PROMPTING_NEW
)